from __future__ import annotations

import logging

logger = logging.getLogger(__name__)

LANG_CODE_CATEGORY_MAP: dict[str, str] = {
    "ar": "Arabic-language SVG",
    "bar": "Bavarian-language SVG",
    "be": "Belarusian-language SVG",
    "bg": "Bulgarian-language SVG",
    "bh": "Bhojpuri-language SVG",
    "bjn": "Banjar-language SVG",
    "blk": "Pa'O-language SVG",
    "bn": "Bengali-language SVG",
    "bs": "Bosnian-language SVG",
    "ca": "Catalan-language SVG",
    "ckt": "Chukchi-language SVG",
    "cs": "Czech-language SVG",
    "cy": "Welsh-language SVG",
    "da": "Danish-language SVG",
    "de": "German-language SVG",
    "el": "Greek-language SVG",
    "en": "English-language SVG",
    "eo": "Esperanto-language SVG",
    "es": "Spanish-language SVG",
    "et": "Estonian-language SVG",
    "eu": "Basque-language SVG",
    "fa": "Persian-language SVG",
    "fi": "Finnish-language SVG",
    "fr": "French-language SVG",
    "fy": "Frisian-language SVG",
    "ga": "Irish-language SVG",
    "gag": "Gagauz-language SVG",
    "gl": "Galician-language SVG",
    "got": "Gothic-language SVG",
    "gu": "Gujarati-language SVG",
    "he": "Hebrew-language SVG",
    "hi": "Hindi-language SVG",
    "hr": "Croatian-language SVG",
    "hsb": "Sorbian-language SVG",
    "ht": "Haitian Creole-language SVG",
    "hu": "Hungarian-language SVG",
    "ia": "Interlingua-language SVG",
    "id": "Indonesian-language SVG",
    "is": "Icelandic-language SVG",
    "isv": "Interslavic-language SVG",
    "it": "Italian-language SVG",
    "ja": "Japanese-language SVG",
    "jv": "Javanese-language SVG",
    "ka": "Georgian-language SVG",
    "kk": "Kazakh-language SVG",
    "kn": "Kannada-language SVG",
    "ko": "Korean-language SVG",
    "ks": "Kashmiri-language SVG",
    "ksh": "Ripuarian-language SVG",
    "ku": "Kurdish-language SVG",
    "ky": "Kyrgyz-language SVG",
    "la": "Latin-language SVG",
    "lb": "Luxembourgish-language SVG",
    "lrc": "Luri-language SVG",
    "lt": "Lithuanian-language SVG",
    "lv": "Latvian-language SVG",
    "mag": "Magahi-language SVG",
    "mai": "Maithili-language SVG",
    "mdf": "Moksha-language SVG",
    "mg": "Malagasy-language SVG",
    "mi": "Maori-language SVG",
    "mk": "Macedonian-language SVG",
    "ml": "Malayalam-language SVG",
    "mn": "Mongolian-language SVG",
    "mr": "Marathi-language SVG",
    "mrj": "Hill Mari-language SVG",
    "ms": "Malay-language SVG",
    "mt": "Maltese-language SVG",
    "my": "Burmese-language SVG",
    "nds": "Low German-language SVG",
    "ne": "Nepali-language SVG",
    "nl": "Dutch-language SVG",
    "no": "Norwegian-language SVG",
    "nrm": "Norman-language SVG",
    "pa": "Punjabi-language SVG",
    "pl": "Polish-language SVG",
    "pms": "Piedmontese-language SVG",
    "prs": "Dari-language SVG",
    "pt": "Portuguese-language SVG",
    "qu": "Quechua-language SVG",
    "rm": "Romansh-language SVG",
    "ro": "Romanian-language SVG",
    "ru": "Russian-language SVG",
    "rue": "Rusyn-language SVG",
    "sa": "Sanskrit-language SVG",
    "sat": "Santali-language SVG",
    "sco": "Scots-language SVG",
    "sd": "Sindhi-language SVG",
    "se": "Northern Sami-language SVG",
    "sh": "Serbo-Croatian-language SVG",
    "si": "Sinhala-language SVG",
    "sk": "Slovak-language SVG",
    "sl": "Slovene-language SVG",
    "smn": "Inari Sami-language SVG",
    "sms": "Skolt Sami-language SVG",
    "so": "Somali-language SVG",
    "sr": "Serbian-language SVG",
    "sv": "Swedish-language SVG",
    "sw": "Swahili-language SVG",
    "syl": "Sylheti-language SVG",
    "ta": "Tamil-language SVG",
    "te": "Telugu-language SVG",
    "th": "Thai-language SVG",
    "tl": "Tagalog-language SVG",
    "tr": "Turkish-language SVG",
    "tt": "Tatar-language SVG",
    "tup": "Tupi-language SVG",
    "udm": "Udmurt-language SVG",
    "uk": "Ukrainian-language SVG",
    "ur": "Urdu-language SVG",
    "uz": "Uzbek-language SVG",
    "vec": "Venetian-language SVG",
    "vi": "Vietnamese-language SVG",
    "wa": "Walloon-language SVG",
    "yi": "Yiddish-language SVG",
    "yo": "Yoruba-language SVG",
    "zh": "Chinese-language SVG",
    "zu": "Zulu-language SVG",
}


def lang_code_category(langcode: str) -> str | None:
    return LANG_CODE_CATEGORY_MAP.get(langcode)


__all__ = [
    "LANG_CODE_CATEGORY_MAP",
    "lang_code_category",
]
